<?php

/**
 * @file
 * Installation file for the Member for hack module.
 */

/**
 * Implements hook_requirements().
 */
function member_for_hack_requirements($phase) {
  if ($phase == 'runtime') {
    $t = get_t();
    $requirements['member_for_hack_sponsor'] = array(
      'title' => 'Sponsor Member for hack',
      'description' => $t('Responding to bug reports, adding new features, and upgrading for major Drupal updates takes significant time and energy.'),
      'severity' => REQUIREMENT_INFO,
      'value' => '<script data-gittip-username="deekayen" data-gittip-widget="button" src="//gttp.co/v1.js"></script>',
    );
    return $requirements;
  }
}
